# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('From', models.CharField(max_length=10)),
                ('To', models.CharField(max_length=10)),
                ('From_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('To_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
